"""Platform artwork shipped with the app.

The home carousel used to borrow whatever cover happened to belong to a
system's first game, which looked arbitrary and depended on scan order.  Now
each platform has its own pair of images, generated by
``scripts/build_platform_art.py`` into ``assets/platforms/``:

* ``background/<key>.jpg`` -- square art, fills the card;
* ``logo/<key>.png``       -- transparent, composited on top of it.

Both are decoded once per (key, size) and kept in a small LRU: the carousel
repaints every frame, and re-decoding a 256x256 JPEG per card per frame is
exactly the kind of thing that quietly costs 10 ms.
"""

from __future__ import annotations

import logging
from pathlib import Path

from ..data.media import fit_bitmap
from ..platform.base import Platform

log = logging.getLogger(__name__)

#: Sub-directories inside the assets root.
_BACKGROUND_DIR = "background"
_LOGO_DIR = "logo"

#: Candidate suffixes per kind, in probe order.
_SUFFIXES: dict[str, tuple[str, ...]] = {
    "background": (".jpg", ".png", ".webp"),
    "logo": (".png", ".webp"),
}

#: Cards are repainted every frame but only a handful are on screen at once.
_CACHE_LIMIT = 32


class PlatformArt:
    """Cached access to the shipped platform backgrounds and logos."""

    def __init__(
        self,
        platform: Platform,
        root: Path | None = None,
        *,
        cache_limit: int = _CACHE_LIMIT,
    ) -> None:
        self._platform = platform
        self._root = Path(root) if root is not None else (
            Path(__file__).resolve().parent.parent / "assets" / "platforms"
        )
        self._cache: dict[tuple[str, str, int, int], object] = {}
        self._order: list[tuple[str, str, int, int]] = []
        self._cache_limit = cache_limit
        self._known: dict[str, bool] | None = None

    # ------------------------------------------------------------------ #
    # Lookup
    # ------------------------------------------------------------------ #

    @property
    def root(self) -> Path:
        return self._root

    def directory_for(self, kind: str) -> Path:
        return self._root / (_BACKGROUND_DIR if kind == "background" else _LOGO_DIR)

    def candidates(self, kind: str, key: str) -> list[Path]:
        """Every existing file that could hold ``kind`` artwork for ``key``."""
        directory = self.directory_for(kind)
        stem = key.casefold()
        return [
            candidate
            for suffix in _SUFFIXES.get(kind, ())
            if (candidate := directory / f"{stem}{suffix}").is_file()
        ]

    def path_for(self, kind: str, key: str) -> Path | None:
        """The first existing file for ``kind``/``key``, or ``None``."""
        found = self.candidates(kind, key)
        return found[0] if found else None

    def has_art(self, key: str) -> bool:
        """Whether we can draw anything at all for this platform."""
        if self._known is None:
            # One walk up front; the carousel asks on every frame.
            known: dict[str, bool] = {}
            for kind in _SUFFIXES:
                directory = self._root / (_BACKGROUND_DIR if kind == "background" else _LOGO_DIR)
                if not directory.is_dir():
                    continue
                for candidate in directory.iterdir():
                    known[candidate.stem.casefold()] = True
            self._known = known
        return key.casefold() in self._known

    # ------------------------------------------------------------------ #
    # Bitmaps
    # ------------------------------------------------------------------ #

    def background(self, key: str, width: int, height: int) -> object | None:
        """Square art scaled into the card's art box, or ``None``."""
        return self._get("background", key, width, height)

    def logo(self, key: str, width: int, height: int) -> object | None:
        """The platform logo, alpha preserved, or ``None``."""
        return self._get("logo", key, width, height)

    def _get(self, kind: str, key: str, width: int, height: int) -> object | None:
        if width <= 0 or height <= 0:
            return None
        cache_key = (kind, key.casefold(), width, height)
        cached = self._cache.get(cache_key)
        if cached is not None:
            return cached

        if not self.candidates(kind, key):
            return None
        bitmap = self._decode(kind, key)
        if bitmap is None:
            return None

        # Logos are composited over the background, so they must fit *inside*
        # the box rather than fill it; fit_bitmap already never upscales.
        scaled = fit_bitmap(bitmap, width, height)
        self._remember(cache_key, scaled)
        return scaled

    def _decode(self, kind: str, key: str) -> object | None:
        """Decode the first candidate this Pillow can actually read.

        Two suffixes can coexist after a format change (a leftover ``.jpg``
        beside the ``.webp`` that replaced it), and a device with a mismatched
        libjpeg fails to open JPEGs that look perfectly fine on disk -- so
        every candidate gets a try, not just the first one.
        """
        for path in self.candidates(kind, key):
            try:
                return self._platform.load_image(path)
            except OSError:
                log.debug("cannot decode %s, trying the next format", path)
        return None

    def _remember(self, key: tuple[str, str, int, int], bitmap: object) -> None:
        self._cache[key] = bitmap
        self._order.append(key)
        while len(self._order) > self._cache_limit:
            self._cache.pop(self._order.pop(0), None)

    def clear(self) -> None:
        self._cache.clear()
        self._order.clear()
        self._known = None
